{
	"title": "Rethrowing errors to handle errors at the local AND global level",
	"description": "The rethrow function is, in my opinion, one of the coolest things ever. <code>rethrow()</code> lets your app catch and handle exceptions locally before rethrowing the exception to log or handle the error at a global level. This is awesomely helpful if you need to undo a transaction, for example, or to recover from any other context-specific situation.",
	"snippet": {
		"type": "script",
		"source": "// First level of error handling\r\n// Say, onError in Application.cfc\r\ntry {\r\n\t// somewhere in app-land...\r\n\ttry {\r\n\t\t// do something error-able\r\n\t\tx = 1 / 0;\r\n\t} catch( any e ) {\r\n\t\t// Recover so we don't bork the app\r\n\t\ttransactionRollback();\r\n\t\t// let the parent-level catch handle error logging.\r\n\t\trethrow();\r\n\t}\r\n} catch( any exception ) {\r\n\tcfparam( name=\"exception.message\", default=\"[no message]\" );\r\n\tcfparam( name=\"exception.detail\", default=\"[no detail]\" );\r\n\r\n\t// Log it with LogBox!\r\n\twriteOutput( \"Logging error with logbox...\" );\r\n\tlogger.error(\r\n\t\t\"Error in cfSnippets app: #exception.message# #exception.detail#\"\r\n\t\texception\r\n\t);\r\n}"
	},
	"cheatsheets": [ "error-handling" ]
}